## library() calls go here
library(conflicted)
library(dotenv)
library(targets)
library(tarchetypes)

library(tidyverse)
library(tidymodels)
library(mrpac.private)
library(xgboost)
library(shiny)
library(rlang)
library(tibble)
library(dplyr)
library(readr)
library(purrr)
library(stringr)
library(shinyWidgets)
library(data.table)
library(gt)
library(glue)
library(table.glue)
library(rintrojs)
library(cmprsk)
library(tidyfast)
library(DT)
library(conflicted)

conflict_prefer(':=', 'data.table')
conflict_prefer("filter", "dplyr")
conflict_prefer("renderDataTable", "DT")



conflict_prefer('filter', 'dplyr')
conflict_prefer('fixed', 'stringr')
